@GameStore.Api_HostAddress = http://localhost:5261

### Create game
POST {{GameStore.Api_HostAddress}}/api/games
Content-Type: application/json

{
  "name": "Super Mario Bros. 3",
  "description": "A classic platform game.",
  "price": 19.99,
  "genreId": 10
}

### Get game
GET {{GameStore.Api_HostAddress}}/api/games/faeaabf8-87a2-4e24-bcee-01b24e6668a1

### Get games
GET {{GameStore.Api_HostAddress}}/api/games?page=1&pageSize=12&search=mario

### Update game
PUT {{GameStore.Api_HostAddress}}/api/games/faeaabf8-87a2-4e24-bcee-01b24e6668a1
Content-Type: application/json

{
  "name": "Celeste",
  "description": "A precise and emotional mountain-climbing platformer.",
  "price": 29.99,
  "genreId": 10,
  "isActive": true
}
