-- Seed genres (12) and games (50).

TRUNCATE TABLE "Games", "Genres" RESTART IDENTITY CASCADE;

INSERT INTO "Genres" ("Id", "Name") VALUES
  (1, 'Action'),
  (2, 'Adventure'),
  (3, 'RPG'),
  (4, 'Strategy'),
  (5, 'Simulation'),
  (6, 'Sports'),
  (7, 'Racing'),
  (8, 'Puzzle'),
  (9, 'Horror'),
  (10, 'Platformer'),
  (11, 'Fighting'),
  (12, 'Shooter');

SELECT setval(pg_get_serial_sequence('"Genres"', 'Id'), (SELECT MAX("Id") FROM "Genres"));

INSERT INTO "Games" ("Id", "Name", "Description", "Price", "GenreId", "CreatedAt", "UpdatedAt", "IsActive", "ImageUrl") VALUES
  (gen_random_uuid(), 'Celeste', 'A precise and emotional mountain-climbing platformer.', 19.99, 10, NOW(), NOW(), TRUE, 'https://upload.wikimedia.org/wikipedia/commons/0/0f/Celeste_box_art_full.png'),
  (gen_random_uuid(), 'Hades', 'Battle out of the Underworld in this rogue-like dungeon crawler.', 24.99, 1, NOW(), NOW(), TRUE, 'https://upload.wikimedia.org/wikipedia/en/c/cc/Hades_cover_art.jpg'),
  (gen_random_uuid(), 'Stardew Valley', 'Build the farm of your dreams in a cozy countryside town.', 14.99, 5, NOW(), NOW(), TRUE, 'https://upload.wikimedia.org/wikipedia/en/f/fd/Logo_of_Stardew_Valley.png'),
  (gen_random_uuid(), 'The Witcher 3', 'Hunt monsters and make hard choices in a vast open world.', 39.99, 3, NOW(), NOW(), TRUE, 'https://upload.wikimedia.org/wikipedia/en/0/0c/Witcher_3_cover_art.jpg'),
  (gen_random_uuid(), 'Portal 2', 'Solve mind-bending puzzles with a portal gun and a sharp-tongued AI.', 9.99, 8, NOW(), NOW(), TRUE, 'https://upload.wikimedia.org/wikipedia/en/f/f9/Portal2cover.jpg'),
  (gen_random_uuid(), 'Hollow Knight', 'Explore a ruined insect kingdom filled with challenging combat.', 14.99, 10, NOW(), NOW(), TRUE, 'https://upload.wikimedia.org/wikipedia/en/d/de/Hollow_Knight_2026_cover_art.jpg'),
  (gen_random_uuid(), 'Civilization VI', 'Lead a civilization from the stone age to the space age.', 59.99, 4, NOW(), NOW(), TRUE, 'https://upload.wikimedia.org/wikipedia/en/3/3b/Civilization_VI_cover_art.jpg'),
  (gen_random_uuid(), 'Forza Horizon 5', 'Open-world racing across a vibrant Mexico.', 69.99, 7, NOW(), NOW(), TRUE, 'https://upload.wikimedia.org/wikipedia/en/8/86/Forza_Horizon_5_cover_art.jpg'),
  (gen_random_uuid(), 'Resident Evil 4 Remake', 'Survive a rural nightmare with refined survival-horror action.', 59.99, 9, NOW(), NOW(), TRUE, 'https://upload.wikimedia.org/wikipedia/en/d/df/Resident_Evil_4_remake_cover_art.jpg'),
  (gen_random_uuid(), 'Street Fighter 6', 'Modern fighting game with deep systems and approachable controls.', 59.99, 11, NOW(), NOW(), TRUE, 'https://upload.wikimedia.org/wikipedia/en/9/94/Street_Fighter_6_box_art.jpg'),
  (gen_random_uuid(), 'Doom Eternal', 'Rip and tear through demonic hordes at blistering speed.', 39.99, 12, NOW(), NOW(), TRUE, 'https://upload.wikimedia.org/wikipedia/en/9/9d/Cover_Art_of_Doom_Eternal.png'),
  (gen_random_uuid(), 'Uncharted 4', 'A globe-trotting treasure-hunting adventure with cinematic set pieces.', 19.99, 2, NOW(), NOW(), TRUE, 'https://upload.wikimedia.org/wikipedia/en/1/1a/Uncharted_4_box_artwork.jpg'),
  (gen_random_uuid(), 'FIFA 23', 'Football simulation with clubs, career modes, and online matches.', 29.99, 6, NOW(), NOW(), TRUE, 'https://upload.wikimedia.org/wikipedia/en/a/a6/FIFA_23_Cover.jpg'),
  (gen_random_uuid(), 'Disco Elysium', 'A narrative RPG where your skills argue with each other.', 39.99, 3, NOW(), NOW(), TRUE, 'https://upload.wikimedia.org/wikipedia/en/0/0d/Disco_Elysium_Poster.jpeg'),
  (gen_random_uuid(), 'Slay the Spire', 'Climb a spire with deck-building combat and endless builds.', 24.99, 4, NOW(), NOW(), TRUE, 'https://upload.wikimedia.org/wikipedia/en/b/b7/Slay_the_spire_cover.jpg'),
  (gen_random_uuid(), 'Animal Crossing: New Horizons', 'Create your island getaway at your own pace.', 49.99, 5, NOW(), NOW(), TRUE, 'https://upload.wikimedia.org/wikipedia/en/1/1f/Animal_Crossing_New_Horizons.jpg'),
  (gen_random_uuid(), 'Sekiro: Shadows Die Twice', 'Master posture combat as a shinobi in a brutal feudal Japan.', 59.99, 1, NOW(), NOW(), TRUE, 'https://upload.wikimedia.org/wikipedia/en/6/6e/Sekiro_art.jpg'),
  (gen_random_uuid(), 'Ori and the Will of the Wisps', 'A beautiful metroidvania with fluid movement and emotional storytelling.', 29.99, 10, NOW(), NOW(), TRUE, 'https://upload.wikimedia.org/wikipedia/en/9/94/Ori_and_the_Will_of_the_Wisps.jpg'),
  (gen_random_uuid(), 'Baba Is You', 'Rewrite the rules of the world to solve inventive puzzles.', 14.99, 8, NOW(), NOW(), TRUE, 'https://upload.wikimedia.org/wikipedia/en/2/28/Baba_is_you_cover_art.jpg'),
  (gen_random_uuid(), 'Gran Turismo 7', 'Detail-focused racing with a huge car collection and tracks.', 69.99, 7, NOW(), NOW(), TRUE, 'https://upload.wikimedia.org/wikipedia/en/1/14/Gran_Turismo_7_cover_art.jpg'),
  (gen_random_uuid(), 'Dead Space Remake', 'Repair a haunted mining ship while managing scarce resources.', 69.99, 9, NOW(), NOW(), TRUE, 'https://upload.wikimedia.org/wikipedia/en/3/36/Dead_Space_2022_Teaser_Art.jpg'),
  (gen_random_uuid(), 'Tekken 8', 'High-intensity 3D fighting with aggressive momentum systems.', 69.99, 11, NOW(), NOW(), TRUE, 'https://upload.wikimedia.org/wikipedia/en/b/b4/Tekken_8_cover_art.jpg'),
  (gen_random_uuid(), 'Titanfall 2', 'Parkour shootouts with a memorable single-player campaign.', 19.99, 12, NOW(), NOW(), TRUE, 'https://upload.wikimedia.org/wikipedia/en/1/13/Titanfall_2.jpg'),
  (gen_random_uuid(), 'Firewatch', 'A first-person mystery set in the Wyoming wilderness.', 19.99, 2, NOW(), NOW(), TRUE, 'https://upload.wikimedia.org/wikipedia/en/a/a5/Firewatch_cover.jpg'),
  (gen_random_uuid(), 'NBA 2K24', 'Basketball simulation with MyCareer, MyTEAM, and ProPlay.', 49.99, 6, NOW(), NOW(), TRUE, 'https://upload.wikimedia.org/wikipedia/en/4/48/NBA_2K24_cover_art.jpg'),
  (gen_random_uuid(), 'Baldur''s Gate 3', 'A deep CRPG powered by D&D 5e rules and player freedom.', 69.99, 3, NOW(), NOW(), TRUE, 'https://upload.wikimedia.org/wikipedia/en/1/12/Baldur%27s_Gate_3_cover_art.jpg'),
  (gen_random_uuid(), 'XCOM 2', 'Tactical turn-based battles against an alien occupation.', 39.99, 4, NOW(), NOW(), TRUE, 'https://upload.wikimedia.org/wikipedia/en/c/c3/XCOM_2_cover_art.jpg'),
  (gen_random_uuid(), 'Microsoft Flight Simulator', 'Photo-realistic flying across the entire planet.', 69.99, 5, NOW(), NOW(), TRUE, 'https://upload.wikimedia.org/wikipedia/en/8/84/Microsoft_Flight_Simulator_2020_cover_art.png'),
  (gen_random_uuid(), 'Devil May Cry 5', 'Stylish combo-driven action against demonic invaders.', 29.99, 1, NOW(), NOW(), TRUE, 'https://upload.wikimedia.org/wikipedia/en/c/cb/Devil_May_Cry_5.jpg'),
  (gen_random_uuid(), 'Super Mario Odyssey', 'Explore imaginative kingdoms with Mario and Cappy.', 49.99, 10, NOW(), NOW(), TRUE, 'https://upload.wikimedia.org/wikipedia/en/8/8d/Super_Mario_Odyssey.jpg'),
  (gen_random_uuid(), 'The Witness', 'Explore an island covered in intricate line puzzles.', 39.99, 8, NOW(), NOW(), TRUE, 'https://upload.wikimedia.org/wikipedia/en/f/f4/The_Witness_cover.jpg'),
  (gen_random_uuid(), 'Need for Speed Unbound', 'Street racing with bold art direction and high-stakes heats.', 49.99, 7, NOW(), NOW(), TRUE, 'https://upload.wikimedia.org/wikipedia/en/d/db/Need_for_Speed_Unbound.png'),
  (gen_random_uuid(), 'Alien: Isolation', 'Hide from a relentless xenomorph aboard a failing space station.', 39.99, 9, NOW(), NOW(), TRUE, 'https://upload.wikimedia.org/wikipedia/en/6/6e/Alien_Isolation.jpg'),
  (gen_random_uuid(), 'Mortal Kombat 1', 'Brutal fighting action with reinvented fighters and fatalities.', 49.99, 11, NOW(), NOW(), TRUE, 'https://upload.wikimedia.org/wikipedia/en/5/5b/Mortal_Kombat_1_key_art.jpeg'),
  (gen_random_uuid(), 'Halo Infinite', 'Sci-fi shooting with an open-world campaign and multiplayer arena.', 39.99, 12, NOW(), NOW(), TRUE, 'https://upload.wikimedia.org/wikipedia/en/1/14/Halo_Infinite.png'),
  (gen_random_uuid(), 'Journey', 'Travel through a mysterious desert toward a distant mountain.', 14.99, 2, NOW(), NOW(), TRUE, 'https://upload.wikimedia.org/wikipedia/en/6/64/Journey_Title_Poster.png'),
  (gen_random_uuid(), 'Rocket League', 'Soccer with rocket-powered cars in chaotic multiplayer matches.', 0.00, 6, NOW(), NOW(), TRUE, 'https://upload.wikimedia.org/wikipedia/commons/e/e0/Rocket_League_coverart.jpg'),
  (gen_random_uuid(), 'Persona 5 Royal', 'Live a double life as a stylish phantom thief in Tokyo.', 59.99, 3, NOW(), NOW(), TRUE, NULL),
  (gen_random_uuid(), 'Age of Empires IV', 'Build empires and command historic battles in real time.', 59.99, 4, NOW(), NOW(), TRUE, 'https://upload.wikimedia.org/wikipedia/en/0/08/Age_of_Empires_IV_Cover_Art.png'),
  (gen_random_uuid(), 'The Sims 4', 'Create people, homes, and stories in a life simulation sandbox.', 39.99, 5, NOW(), NOW(), TRUE, 'https://upload.wikimedia.org/wikipedia/en/7/7f/Sims4_Rebrand.png'),
  (gen_random_uuid(), 'Bayonetta 3', 'Over-the-top stylish action across multiple realities.', 59.99, 1, NOW(), NOW(), TRUE, 'https://upload.wikimedia.org/wikipedia/en/f/fe/Bayonetta_3_cover.webp'),
  (gen_random_uuid(), 'Rayman Legends', 'Side-scrolling platforming packed with musical levels and co-op.', 19.99, 10, NOW(), NOW(), TRUE, 'https://upload.wikimedia.org/wikipedia/en/f/f6/Rayman_Legends_Box_Art.jpg'),
  (gen_random_uuid(), 'Tetris Effect', 'Classic falling-block puzzles wrapped in audiovisual spectacle.', 39.99, 8, NOW(), NOW(), TRUE, 'https://upload.wikimedia.org/wikipedia/en/a/ae/Tetris_Effect_cover.jpg'),
  (gen_random_uuid(), 'F1 24', 'Official Formula 1 racing with career and online championships.', 69.99, 7, NOW(), NOW(), TRUE, 'https://upload.wikimedia.org/wikipedia/en/5/55/F1_24_cover_art.jpg'),
  (gen_random_uuid(), 'Outlast 2', 'Run and hide through a terrifying rural cult scenario.', 29.99, 9, NOW(), NOW(), TRUE, 'https://upload.wikimedia.org/wikipedia/en/1/1b/Outlast2.png'),
  (gen_random_uuid(), 'Guilty Gear Strive', 'Flashy anime fighting with expressive characters and netcode.', 39.99, 11, NOW(), NOW(), TRUE, 'https://upload.wikimedia.org/wikipedia/en/7/7d/Guilty_Gear_Strive.jpg'),
  (gen_random_uuid(), 'Overwatch 2', 'Team-based hero shootouts across objective modes.', 0.00, 12, NOW(), NOW(), TRUE, 'https://upload.wikimedia.org/wikipedia/en/8/89/Overwatch_2_Steam_artwork.jpg'),
  (gen_random_uuid(), 'Outer Wilds', 'Explore a tiny solar system stuck in a 22-minute time loop.', 24.99, 2, NOW(), NOW(), TRUE, 'https://upload.wikimedia.org/wikipedia/en/f/f6/Outer_Wilds_Steam_artwork.jpg'),
  (gen_random_uuid(), 'Tony Hawk''s Pro Skater 1+2', 'Classic skateboarding levels remade with modern polish.', 39.99, 6, NOW(), NOW(), TRUE, 'https://upload.wikimedia.org/wikipedia/en/8/8f/Tony_Hawk_Pro_Skater_Remaster_cover_art.png'),
  (gen_random_uuid(), 'Elden Ring', 'An open-world action RPG filled with secrets and punishing bosses.', 59.99, 3, NOW(), NOW(), TRUE, 'https://upload.wikimedia.org/wikipedia/en/b/b9/Elden_Ring_Box_art.jpg');
